### ISSUE TITLE
parser failed wth "ParameterNotUnderstood: Could not find an action for Header Parameter 'ppt''"

### ISSUE THREAD

**Issue by veluvarti835** [brianloveswords/python-jws#36]
>>> payload ={"alg":"ES256","typ":"passport","ppt":"shaken","x5u":"https://wiresharkserver.mtimslab.atttest.com/vesper/dig-sig.crt"}
>>> payload ={}
>>> header  = {"alg":"ES256","typ":"passport","ppt":"shaken","x5u":"https://wiresharkserver.mtimslab.atttest.com/vesper/dig-sig.crt"}
>>> payload = {"attest":"A","dest":{"tn":["+12249587065"]},"iat":1504163217,"orig":{"tn":"+12249587035"},"origid":"6cf14ce7-5c58-403c-8982-07f11b8680d5"}
>>> signature = jws.sign(header, payload, 'secret')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/jws/__init__.py", line 23, in sign
    header.process(data, 'sign')
  File "/usr/lib/python2.7/site-packages/jws/header.py", line 67, in process
    instance = cls(param, data['header'][param], data)
  File "/usr/lib/python2.7/site-packages/jws/header.py", line 10, in __init__
    self.value = self.clean(value)
  File "/usr/lib/python2.7/site-packages/jws/header.py", line 30, in clean
    raise ParameterNotUnderstood("Could not find an action for Header Parameter '%s'" % self.name)
jws.exceptions.ParameterNotUnderstood: Could not find an action for Header Parameter 'ppt'

**Comment by veluvarti835** [comment]
After adding ppt header in to known headers  got below error , can some one help me to resolve it 
KNOWN_HEADERS = {
    # REQUIRED, signing algo, see signing_methods
    'alg': Algorithm,
    # OPTIONAL, type of signed content
    'typ': GenericString,
    # OPTIONAL, JSON Key URL. See http://self-issued.info/docs/draft-jones-json-web-key.html
    'jku': VerifyNotImplemented,
     # OPTIONAL, key id, hint for which key to use.
    'kid': VerifyNotImplemented,
    # OPTIONAL, x.509 URL pointing to certificate or certificate chain
    'x5u': VerifyNotImplemented,
    # OPTIONAL, x.509 certificate thumbprint
    'x5t': VerifyNotImplemented,
    # OPTIONAL, type of signed content
    'ppt': GenericString,
}
>>> signature = jws.sign(header, payload, 'secret')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/jws/__init__.py", line 29, in sign
    signature = signer(_signing_input(head, payload, is_json), key)
  File "/usr/lib/python2.7/site-packages/jws/algos.py", line 127, in sign
    return key.sign(msg, hashfunc=self.hasher)
AttributeError: 'str' object has no attribute 'sign'
>>>
